name = "imgbed"
compatibility_date = "2024-05-01"

[assets]
directory = "."

exclude = [
  "node_modules/**",   # 排除所有依赖项（这是导致错误的根源）
  ".git/**",           # 排除 Git 仓库信息
  ".github/**",        # 排除 GitHub Actions 等配置
  "wrangler.toml",     # 排除 wrangler 配置文件本身
  "package.json",      # 排除包管理文件
  "package-lock.json", # 排除锁文件
  "README.md",         # 排除说明文件
  ".vscode/**",        # 排除 VSCode 编辑器配置
  "*.log"              # 排除日志文件
]
